version: '3.7'
services:
  nodejs:
    image: "fitrakz/backend"
    ports:
      - "3000:3000"
    networks:
      - samplenet
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
    environment:
      ACCESS_TOKEN_SECRET: 0d1afdb986e6ea2dba64dec53697bd0757380f47442e2f85d0139e58eb035567
      REFRESH_TOKEN_SECRET: 7afb273497b3750a8a1e27c54101092b7dca88cc112b20326e59258b99abbdc0
      DB_PASSWORD: 12341234
      DB_USER: mydb
      DB_HOST: 18.234.103.79
      DB_PORT: 5433
      DB_NAME: cashier-restaurant
      PORT_REDIS: 6379
      HOST_REDIS: 18.234.103.79
      PORT: 3000

  nodejs2:
    image: "fitrakz/backend"
    ports:
      - "3001:3000"
    networks:
      - samplenet
    environment:
      ACCESS_TOKEN_SECRET: 0d1afdb986e6ea2dba64dec53697bd0757380f47442e2f85d0139e58eb035567
      REFRESH_TOKEN_SECRET: 7afb273497b3750a8a1e27c54101092b7dca88cc112b20326e59258b99abbdc0
      DB_PASSWORD: 12341234
      DB_USER: mydb
      DB_HOST: 18.234.103.79
      DB_PORT: 5433
      DB_NAME: cashier-restaurant
      PORT_REDIS: 6379
      HOST_REDIS: 18.234.103.79
      PORT: 3000

  my-app:
    container_name: my-app
    image: "fitrakz/staging-cashier-app"
    restart: always
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d/
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
      - nodejs:nodejs
      - nodejs2:nodejs2
    networks:
      - samplenet

  certbot:
     image: certbot/certbot:latest
     command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email in4644591@gmail.com --agree-tos --no-eff-email -d centz.dimasrio.com
     volumes:
       - ./certbot/conf/:/etc/letsencrypt
       - ./certbot/logs/:/var/log/letsencrypt
       - ./certbot/data:/usr/share/nginx/html/letsencrypt

networks:
    samplenet:
