version: '3.7'
services:
  nodejs:
    image: "fitrakz/backend"
    ports:
      - "3000:3000"
    networks:
      - samplenet
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M

  nodejs2:
    image: "fitrakz/backend"
    ports:
      - "3001:3000"
    networks:
      - samplenet

  my-app:
    container_name: my-app
    image: "fitrakz/frontend"
    ports:
      - '8081:8080'
    networks:
      - samplenet

networks:
    samplenet:
